### ISSUE TITLE
Dark theme signal bar highlight colour is very hard to see

### ISSUE THREAD

**Issue by pdesgrip** [smartift/grail#80]
This could be of course a contrast/brightness issue with my monitor but I run at fairly standard settings and find the vertical highlight bar that moves with the mouse across the chart is too light to see properly.

See screenshot.

![image](https://user-images.githubusercontent.com/16015766/37378234-a5455bac-272e-11e8-811d-62b4f24ef2f8.png)

**Comment by guytp** [comment]
Also improved light theme to make both slightly more visible
