### ISSUE TITLE
Add Hovertips to UI

### ISSUE THREAD

**Issue by pdesgrip** [smartift/grail#9]
Adding hovertips for the GRAIL UI elements would be beneficial for users.

**Comment by guytp** [comment]
Can you give an idea of content for each hovertip?  Is this in addition to right hand side hover-over text that's present or more info, or both - more info and in a different place?

**Comment by pdesgrip** [comment]
For instance on the '+' button I might use 'open new chart window' or a shorter version if that is too long. 
I am more talking about control elements than the charts. Perhaps 'zoom in/out' on the slider control too?

**Comment by guytp** [comment]
Accepted for alpha
